description: "\u0412\u0445\u043E\u0434 USB\n\u041F\u043E\u043A\u0430\u043D\u0430\u043B\
  \u044C\u043D\u044B\u0439 \u0432\u044B\u0445\u043E\u0434 \u043D\u0430 4 \u043F\u043E\
  \u043B\u043E\u0441\u044B\nFIR \u043A\u0440\u043E\u0441\u0441\u043E\u0432\u0435\u0440"
devices:
  adjust_period: null
  capture:
    channels: 2
    device: plughw:CARD=UAC2Gadget,DEV=0
    format: S24LE
    type: Alsa
  capture_samplerate: 48000
  chunksize: 4096
  enable_rate_adjust: true
  playback:
    channels: 8
    device: hw:CARD=OUT8CH,DEV=0
    format: S24LE
    type: Alsa
  queuelimit: null
  rate_measure_interval: null
  resampler: null
  samplerate: 48000
  silence_threshold: null
  silence_timeout: null
  stop_on_rate_change: null
  target_level: null
  volume_ramp_time: null
filters:
  Bass:
    description: null
    parameters:
      freq: 85
      gain: 0
      slope: 0.9
      type: Lowshelf
    type: Biquad
  Delay0:
    description: null
    parameters:
      delay: 1.3
      subsample: false
      unit: ms
    type: Delay
  Delay1:
    description: null
    parameters:
      delay: 0.1
      subsample: false
      unit: ms
    type: Delay
  Delay2:
    description: null
    parameters:
      delay: 1.3
      subsample: false
      unit: ms
    type: Delay
  Delay3:
    description: null
    parameters:
      delay: 0.1
      subsample: false
      unit: ms
    type: Delay
  Delay4:
    description: null
    parameters:
      delay: 1.18
      subsample: false
      unit: ms
    type: Delay
  Delay5:
    description: null
    parameters:
      delay: 0
      subsample: false
      unit: ms
    type: Delay
  Delay6:
    description: null
    parameters:
      delay: 0
      subsample: false
      unit: ms
    type: Delay
  Delay7:
    description: null
    parameters:
      delay: 0
      subsample: false
      unit: ms
    type: Delay
  Gain0:
    description: null
    parameters:
      gain: -13
      inverted: false
      mute: false
      scale: dB
    type: Gain
  Gain1:
    description: null
    parameters:
      gain: -13
      inverted: false
      mute: false
      scale: dB
    type: Gain
  Gain2:
    description: null
    parameters:
      gain: -11
      inverted: false
      mute: false
      scale: dB
    type: Gain
  Gain3:
    description: null
    parameters:
      gain: -11
      inverted: false
      mute: false
      scale: dB
    type: Gain
  Gain4:
    description: null
    parameters:
      gain: 0
      inverted: false
      mute: false
      scale: dB
    type: Gain
  Gain5:
    description: null
    parameters:
      gain: 0
      inverted: false
      mute: false
      scale: dB
    type: Gain
  Gain6:
    description: null
    parameters:
      gain: 0
      inverted: false
      mute: false
      scale: dB
    type: Gain
  Gain7:
    description: null
    parameters:
      gain: 0
      inverted: false
      mute: false
      scale: dB
    type: Gain
  GainInL:
    description: null
    parameters:
      gain: 0
      inverted: false
      mute: false
      scale: dB
    type: Gain
  GainInR:
    description: null
    parameters:
      gain: 0
      inverted: false
      mute: false
      scale: dB
    type: Gain
  High:
    description: null
    parameters:
      filename: ../coeffs/high-4500_$samplerate$.txt
      format: TEXT
      read_bytes_lines: 0
      skip_bytes_lines: 0
      type: Raw
    type: Conv
  L-phase:
    description: null
    parameters:
      filename: ../coeffs/L-phase.txt
      format: TEXT
      read_bytes_lines: 0
      skip_bytes_lines: 0
      type: Raw
    type: Conv
  Low:
    description: null
    parameters:
      filename: ../coeffs/midbas-70-280_$samplerate$.txt
      format: TEXT
      read_bytes_lines: 0
      skip_bytes_lines: 0
      type: Raw
    type: Conv
  Mid:
    description: null
    parameters:
      filename: ../coeffs/midrange-280-4500_$samplerate$.txt
      format: TEXT
      read_bytes_lines: 0
      skip_bytes_lines: 0
      type: Raw
    type: Conv
  R-phase:
    description: null
    parameters:
      filename: ../coeffs/R-phase.txt
      format: TEXT
      read_bytes_lines: 0
      skip_bytes_lines: 0
      type: Raw
    type: Conv
  Sub:
    description: null
    parameters:
      filename: ../coeffs/sub-70_$samplerate$.txt
      format: TEXT
      read_bytes_lines: 0
      skip_bytes_lines: 0
      type: Raw
    type: Conv
  Treble:
    description: null
    parameters:
      freq: 6500
      gain: 0
      slope: 0.7
      type: Lowshelf
    type: Biquad
mixers:
  Main Mixer 1:
    channels:
      in: 2
      out: 8
    description: null
    mapping:
    - dest: 0
      mute: false
      sources:
      - channel: 0
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 1
      mute: false
      sources:
      - channel: 1
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 2
      mute: false
      sources:
      - channel: 0
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 3
      mute: false
      sources:
      - channel: 1
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 4
      mute: false
      sources:
      - channel: 0
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 5
      mute: false
      sources:
      - channel: 1
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 6
      mute: false
      sources:
      - channel: 0
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 7
      mute: false
      sources:
      - channel: 1
        gain: 0
        inverted: false
        mute: false
        scale: dB
pipeline:
- bypassed: null
  channel: 0
  description: null
  names:
  - GainInL
  type: Filter
- bypassed: null
  channel: 1
  description: null
  names:
  - GainInR
  type: Filter
- bypassed: null
  description: null
  name: Main Mixer 1
  type: Mixer
- bypassed: null
  channel: 6
  description: null
  names:
  - High
  - Gain0
  - Delay0
  type: Filter
- bypassed: null
  channel: 7
  description: null
  names:
  - High
  - Gain1
  - Delay1
  type: Filter
- bypassed: null
  channel: 4
  description: null
  names:
  - Mid
  - Gain2
  - Delay2
  type: Filter
- bypassed: null
  channel: 5
  description: null
  names:
  - Mid
  - Gain3
  - Delay3
  type: Filter
- bypassed: null
  channel: 2
  description: null
  names:
  - Low
  - Gain4
  - Delay4
  type: Filter
- bypassed: null
  channel: 3
  description: null
  names:
  - Low
  - Gain5
  - Delay5
  type: Filter
- bypassed: null
  channel: 0
  description: null
  names:
  - Sub
  - Gain6
  - Delay6
  type: Filter
- bypassed: null
  channel: 1
  description: null
  names:
  - Sub
  - Gain7
  - Delay7
  type: Filter
processors: {}
title: "2 \u0412\u0445\u043E\u0434\u0430 8 \u0432\u044B\u0445\u043E\u0434\u043E\u0432\
  \ 4 \u043F\u043E\u043B\u043E\u0441\u044B \u041A\u0440\u043E\u0441\u0441\u043E\u0432\
  \u0435\u0440 FIR"
